"""Graph API lead retrieval, pinned to one API version and with upfront
token-scope validation -- built specifically to fix the "GraphMethodException
100 when retrieving test lead" failure from the real community thread this
product is grounded in (docs/root_cause_notes.md). That thread had every
Meta-UI-visible permission granted and still failed; the most likely cause
Meta's own error message never surfaces is a token missing the
`leads_retrieval` scope specifically, or generated by a user without an
advertiser role on the ad account the lead's form belongs to -- so this
client checks scopes *before* the call that would otherwise fail opaquely,
and raises a diagnostic that says which of those two it probably is.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import httpx
from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_exponential

_REQUIRED_SCOPES = ("ads_management", "leads_retrieval", "pages_show_list", "pages_read_engagement")
_GRAPH_BASE = "https://graph.facebook.com"


class TokenScopeError(RuntimeError):
    """Raised when the configured Page Access Token is missing a scope Graph
    API needs for lead retrieval -- distinct from a transient failure because
    retrying will never fix it; the fix is regenerating the token."""


class LeadRetrievalError(RuntimeError):
    """Wraps a Graph API error response with a message a human can act on,
    instead of surfacing Facebook's opaque GraphMethodException code alone."""

    def __init__(self, message: str, *, graph_error: dict[str, Any] | None = None) -> None:
        super().__init__(message)
        self.graph_error = graph_error


@dataclass(frozen=True)
class GraphLead:
    raw: dict[str, Any]


def _transient(exc: BaseException | None) -> bool:
    # Retry only on network/5xx -- a 400 GraphMethodException is not transient
    # and retrying it just burns the rate limit for no benefit.
    if isinstance(exc, httpx.TransportError):
        return True
    if isinstance(exc, httpx.HTTPStatusError):
        return exc.response.status_code >= 500
    return False


async def validate_token_scopes(access_token: str, api_version: str) -> list[str]:
    """Returns the list of required scopes NOT granted to this token. Call
    once at startup (or lazily, cached) rather than per-lead -- this is a
    diagnostic check, not part of the per-lead hot path."""
    url = f"{_GRAPH_BASE}/{api_version}/me/permissions"
    async with httpx.AsyncClient(timeout=10.0) as client:
        response = await client.get(url, params={"access_token": access_token})
    response.raise_for_status()
    granted = {
        p["permission"] for p in response.json().get("data", []) if p.get("status") == "granted"
    }
    return [scope for scope in _REQUIRED_SCOPES if scope not in granted]


@retry(
    retry=retry_if_exception_type((httpx.TransportError, httpx.HTTPStatusError)),
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=1, max=8),
    reraise=True,
)
async def _get_with_retry(
    client: httpx.AsyncClient, url: str, params: dict[str, str]
) -> httpx.Response:
    response = await client.get(url, params=params)
    if _transient(_as_status_error(response)):
        response.raise_for_status()
    return response


def _as_status_error(response: httpx.Response) -> httpx.HTTPStatusError | None:
    if response.status_code < 400:
        return None
    return httpx.HTTPStatusError("error", request=response.request, response=response)


async def fetch_lead(leadgen_id: str, access_token: str, api_version: str) -> GraphLead:
    url = f"{_GRAPH_BASE}/{api_version}/{leadgen_id}"
    params = {"access_token": access_token, "fields": "id,form_id,ad_id,created_time,field_data"}

    async with httpx.AsyncClient(timeout=15.0) as client:
        response = await _get_with_retry(client, url, params)

    if response.status_code >= 400:
        body = (
            response.json()
            if response.headers.get("content-type", "").startswith("application/json")
            else {}
        )
        error = body.get("error", {})
        if error.get("code") == 100:
            missing = await validate_token_scopes(access_token, api_version)
            hint = (
                f"token is missing scope(s): {', '.join(missing)} -- regenerate it with these granted"
                if missing
                else "all required scopes are granted; this is likely a Page token generated by a "
                "user without an advertiser role on the ad account this lead's form belongs to"
            )
            raise LeadRetrievalError(
                f"Graph API refused to retrieve lead {leadgen_id} (GraphMethodException 100, "
                f"'{error.get('message', 'no message')}'). Diagnosis: {hint}.",
                graph_error=error,
            )
        raise LeadRetrievalError(
            f"Graph API error retrieving lead {leadgen_id}: "
            f"{error.get('message', response.text)} (code {error.get('code')})",
            graph_error=error,
        )

    return GraphLead(raw=response.json())
